### ISSUE TITLE
composer.json should require EXT:vhs

### ISSUE THREAD

**Issue by Treupo** [joachimruhs/myflat#1]
As EXT:vhs is required by ext_emconf, the composer.json should require the extension, too.

When installing the EXT:myflat, the EXT:vhs was not installed.

**Comment by Treupo** [comment]
The EXT:vhs is available in version 6.0.4 but in ext_emconf, the version 2.4.0 is required. Maybe it can be updated.

**Comment by joachimruhs** [comment]
Hello,
I have fixed it...
