### ISSUE TITLE
div is not closed in Multirowcalendar.html

### ISSUE THREAD

**Issue by PhilippKuhlmay** [joachimruhs/myflat#2]
It seems that there is a closing div-tag missing inside EXT:myflat/Resources/Private/Templates/Flat/Multirowcalendar.html

https://github.com/joachimruhs/myflat/blob/24221bde32e13b1e6e0358ce5206a2f28cf89996/Resources/Private/Templates/Flat/Multirowcalendar.html#L35

**Comment by joachimruhs** [comment]
Missing </div> inserted
