### ISSUE TITLE
Typos in class Book

### ISSUE THREAD

**Issue by Hawkeye1909** [joachimruhs/myflat#3]
I guess the property "feueruid" in the Book object should rather be named "feuseruid", right?

And in the function setNotes ([https://github.com/joachimruhs/myflat/blob/d295d122c342ab3fb99479e4602275ab98efc30e/Classes/Domain/Model/Book.php#L125](url)) it should be:
`$this->notes = $notes;`

**Comment by joachimruhs** [comment]
Hello,
thx for reporting - I fixed that.
The function/value are not used at the time.
