### ISSUE TITLE
Error in german translation

### ISSUE THREAD

**Issue by anderlk** [joachimruhs/myflat#5]
In German translation the shortname of sunday has a spelling mistake. Correct is "So"

![Bildschirmfoto 2023-07-29 um 11 53 26](https://github.com/joachimruhs/myflat/assets/12695520/f6eef63e-35f4-4d22-a848-76ab8f6d97ae)

Regards Andreas

**Comment by joachimruhs** [comment]
Hi,
thx for reporting - I fixed it on the translation server.

**Comment by anderlk** [comment]
Thanks for very fast bugfix,
Regards Andreas
