### ISSUE TITLE
Error 503 at availability check with wrong dates

### ISSUE THREAD

**Issue by tobiasschaeferptb** [joachimruhs/myflat#7]
Hello,

when I use the availability check with wrong dates (arrival date after departure date) it leads to an error 503:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: You have requested a non-existent service "". | Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException thrown in file typo3cms/typo3_src-12.4.19/vendor/symfony/dependency-injection/Container.php in line 243
The TYPO3 version ist 12.4.19 and the myflat version is 1.2.1.
It would be good if the error message would inform the user what he/she did wrong.

Best regards,
Tobias Schäfer

**Comment by joachimruhs** [comment]
Hi,
thx for reporting.
Change in FlatControlle line 146 to
                ->withControllerName('Flat')

Will be includes in next Version.
Regards
Joachim Ruhs

**Comment by tobiasschaeferptb** [comment]
Hello Joachim,

thank you for the quick fix. 

Best regards,
Tobias Schäfer
